# Site settings
title: Moidul Hasan
general_email: moidulhasan1821@gmail.com
academic_email: 1918030@buet.ac.bd

description: > # this means to ignore newlines until "baseurl:"
  BUET BME Graduate | Fall'26 MS/PhD Aspirant | Deep Learning · Medical Imaging · Clinical Decision Support Systems
baseurl: "" # the subpath of your site, e.g. /blog/

url: "https://moidh062.github.io" # the base hostname & protocol for your site

# twitter_username: jekyllrb
github_username: moidh062
linkedin_username: moidh062
facebook_username: moid062
# feel free to add other links here; you will have to add the SVG icon in _layouts/footer.html

# Build settings
markdown: kramdown

kramdown:
  math_engine: mathjax

# Other options
permalink: blog/:year/:month/:title
